name: EVM Workflow

on:
  # We want to trigger these jobs in every branch.
  push:
    # But do not trigger them when only `md` files were modified.
    paths-ignore:
      - '**.md'

# `FORCE_COLOR` is used by `chalk`, which is used internally by `mocha`.
# https://github.com/chalk/chalk#supportscolor
# https://github.com/orgs/community/discussions/26944#discussioncomment-3254075
env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn lint
      - run: yarn bundle

  test:
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest, ubuntu-latest]
        # https://nodejs.dev/en/about/releases/
        node: [16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn test:check
      - run: yarn test:smoke

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn coverage

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: node dist/examples/Compound.js
      - run: node examples/DAI.js
      - run: node examples/unicornToken.js
      - run: node examples/usdc-proxy.js
